DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(70) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    nns VARCHAR(30) NOT NULL,
    num_tarjeta VARCHAR(50) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    clave VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);


DROP TABLE IF EXISTS MEDICOS;
CREATE TABLE MEDICOS(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(70) NOT NULL,
    ncol VARCHAR(30) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    clave VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS CITAS;
CREATE TABLE CITAS(
    id INT NOT NULL AUTO_INCREMENT,
    attr11 INT NOT NULL,
    fecha_hora DATETIME NOT NULL,
    motivo VARCHAR(200) NOT NULL,
    medico INT NOT NULL,
    paciente INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (medico) REFERENCES MEDICOS(id),
    FOREIGN KEY (paciente) REFERENCES PACIENTES(id)
);


DROP TABLE IF EXISTS DIAGNOSTICO;
CREATE TABLE DIAGNOSTICO(
    id INT NOT NULL AUTO_INCREMENT,
    enfermedad VARCHAR(70) NOT NULL,
    valoracion VARCHAR(200) NOT NULL,
    cita_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cita_id) REFERENCES CITAS(id)
);


DROP TABLE IF EXISTS MEDICO_PACIENTE;
CREATE TABLE MEDICO_PACIENTE(
    medico_id INT NOT NULL,
    paciente_id INT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE(medico_id,paciente_id)
);
